import { Providers } from "../provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="container w-full m-auto px-4 py-10">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
