import { generateID } from "@/lib/common";

export const FORM_ENTITIES_NAME = {
  STEPCONTAINER: "step-container",
  INPUTTEXTFIELD: "text-field",
  INPUTMULTILINE: "multiline-text-field",
  CHECKBOX: "checkbox",
  RADIOGROUP: "radio-group",
  SELECTDROPDOWN: "select-drop-down",
  DATEFIELD: "date-field",
  TIMEFIELD: "time-field",
  FILEUPLOAD: "file-upload",
  IMAGEUPLOAD: "image-upload",
  TOGGLE: "toggle",
  CHECKLIST: "checklist",
  SIGNATURE: "signature",
  MULTICHOICES: "multi-choices",
  SCANCODE: "scan-code",
  VERIFIEDID: "verified-id",
  INFORMATION: "information",
};

export const FORM_COMPONENTS = {
  CONTROL: "control",
  CONTAINER: "container",
};

export const FORM_STATUS = {
  DRAFT: "draft",
  PUBLISHED: "published",
};

export const FORM_PAGE = [
  {
    id: "",
    controlName: FORM_ENTITIES_NAME.STEPCONTAINER,
    displayText: "Block",
    itemType: FORM_COMPONENTS.CONTAINER,
    icon: "bi bi-building",
    heading: "Block Name",
    subHeading: "Block Text (optional)",
    skipAble: false,
    type: "INPUT",
  },
];

export const FORM_ENTITIES = [
  {
    id: "",
    controlName: FORM_ENTITIES_NAME.FILEUPLOAD,
    displayText: "Upload",
    description: "Some Description about the field",
    labelName: "Label for File Upload",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "fas fa-cloud-upload-alt",
    required: false,
    category: "media-elements",
    containerId: "",
    placeholder: "Placeholder for File Upload",
    name: "File Upload",
    sequence: 0,
  },
  {
    id: "",
    controlName: FORM_ENTITIES_NAME.RADIOGROUP,
    displayText: "Radio",
    description: "Some Description about the field",
    labelName: "Label for Radio",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "bi bi-dot-circle",
    required: false,
    category: "other-elements",
    items: [
      {
        id: generateID(),
        value: "Button__-1",
        label: "Button 1",
      },
      {
        id: generateID(),
        value: "Button__-2",
        label: "Button 2",
      },
    ],

    containerId: "",
    placeholder: "Placeholder for Radio",
    name: "Radio",
    sequence: 0,
  },

  {
    id: "",
    controlName: FORM_ENTITIES_NAME.INPUTTEXTFIELD,
    displayText: "Text Field",
    description: "Some Description about the field",
    labelName: "Text Field",
    itemType: FORM_COMPONENTS.CONTROL,
    dataType: "text",
    icon: "fas fa-text-height",
    required: false,
    category: "text-elements",

    containerId: "",
    placeholder: "Placeholder for Text Field",
    name: "Text Field",
    sequence: 0,
  },

  {
    id: "",
    controlName: FORM_ENTITIES_NAME.SELECTDROPDOWN,
    displayText: "Dropdown",
    description: "Some Description about the field",
    labelName: "Label for Dropdown",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "bi bi-caret-square-down",
    required: false,
    items: [
      {
        id: generateID(),
        value: "Option__-1",
        label: "Option 1",
      },
      {
        id: generateID(),
        value: "Option__-2",
        label: "Option 2",
      },
    ],
    category: "other-elements",

    containerId: "",
    placeholder: "Placeholder for Select",
    name: "Dropdown",
    sequence: 0,
  },
  // PHONE
  {
    id: "",
    controlName: FORM_ENTITIES_NAME.DATEFIELD,
    displayText: "Date Picker",
    description: "Some Description about the field",
    labelName: "Label for Date",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "bi bi-calendar",
    required: false,
    category: "date-elements",

    containerId: "",
    name: "Date Field",
    placeholder: "Placeholder for Date Field",
    sequence: 0,
  },
  // MULTISELECT
  {
    id: "",
    controlName: FORM_ENTITIES_NAME.IMAGEUPLOAD,
    displayText: "Image",
    description: "Some Description about the field",
    labelName: "Label for Image Upload",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "bi bi-image",
    required: false,
    category: "media-elements",
    containerId: "",
    name: "Image Upload",
    placeholder: "Placeholder for Image Upload",
    sequence: 0,
  },
  {
    id: "",
    controlName: FORM_ENTITIES_NAME.SIGNATURE,
    displayText: "Signature",
    description: "Some Description about the field",
    labelName: "Label for Signature",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "fa fa-signature",
    required: false,
    category: "other-elements",
    containerId: "",
    name: "Signature Field",
    sequence: 0,
    placeholder: "Placeholder for Signature",
  },

  {
    id: "",
    controlName: FORM_ENTITIES_NAME.CHECKBOX,
    displayText: "Check Box",
    description: "Some Description about the field",
    labelName: "Label for Checkbox",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "bi bi-check-square",
    required: false,
    category: "other-elements",
    items: [
      {
        id: generateID(),
        value: "Button__-1",
        label: "Button 1",
      },
      {
        id: generateID(),
        value: "Button__-2",
        label: "Button 2",
      },
    ],
    containerId: "",
    name: "Checkbox",
    sequence: 0,
    placeholder: "Place Holder Checkbox",
  },

  {
    id: "",
    controlName: FORM_ENTITIES_NAME.INFORMATION,
    displayText: "Title/Paragraph Text",
    description: "Some Description about the field",
    labelName: "Label for information",
    itemType: FORM_COMPONENTS.CONTROL,
    icon: "bi bi-check-square",
    required: false,
    category: "other-elements",
    containerId: "",
    name: "information",
    sequence: 0,
    placeholder: "Place Holder Information",
  },
];
